/**
 * Dummy Questions Data
 *
 * Sample question data for development and testing purposes
 * This file contains mock question objects that match the expected question structure
 */

export const dummyQuestions = [
  {
    id: 1,
    question: 'ما هي عاصمة المملكة العربية السعودية؟',
    type: 'multipleChoice',
    category: 'Ministerial',
    correctAnswer: 'choiceA',
    choices: ['الرياض', 'جدة', 'الدمام', 'المدينة المنورة'],
    questionImage: null,
    curriculumId: 1,
    subjectId: 1,
    unitId: 1,
    lessonId: 1,
    year: '2024',
    formNumber: '1',
    grade: 'المرحلة الابتدائية',
    subject: 'الرياضيات',
    unit: 'الوحدة الأولى',
    lesson: 'الدرس الأول',
    addedBy: 'أحمد محمد',
  },
  {
    id: 2,
    question: 'ما هو ناتج جمع 5 + 3؟',
    type: 'multipleChoice',
    category: 'Enrichment',
    correctAnswer: 'choiceB',
    choices: ['6', '8', '7', '9'],
    questionImage: null,
    curriculumId: 1,
    subjectId: 1,
    unitId: 1,
    lessonId: 2,
    year: null,
    formNumber: null,
    curriculum: 'المرحلة الابتدائية',
    subject: 'الرياضيات',
    unit: 'الوحدة الأولى',
    lesson: 'الدرس الثاني',
    addedBy: 'فاطمة علي',
  },
  {
    id: 3,
    question: 'هل الشمس كوكب؟',
    type: 'trueFalse',
    category: 'Ministerial',
    correctAnswer: 'False',
    choices: null,
    questionImage: null,
    curriculumId: 2,
    subjectId: 2,
    unitId: 2,
    lessonId: 3,
    year: '2024',
    formNumber: '2',
    curriculum: 'المرحلة المتوسطة',
    subject: 'العلوم',
    unit: 'الوحدة الثانية',
    lesson: 'الدرس الثالث',
    addedBy: 'خالد أحمد',
  },
  {
    id: 4,
    question: 'ما هو أكبر كوكب في المجموعة الشمسية؟',
    type: 'multipleChoice',
    category: 'Enrichment',
    correctAnswer: 'choiceC',
    choices: ['الأرض', 'المريخ', 'المشتري', 'زحل'],
    questionImage: 'https://example.com/planet-image.jpg',
    curriculumId: 2,
    subjectId: 2,
    unitId: 2,
    lessonId: 4,
    year: null,
    formNumber: null,
    curriculum: 'المرحلة المتوسطة',
    subject: 'العلوم',
    unit: 'الوحدة الثانية',
    lesson: 'الدرس الرابع',
    addedBy: 'سارة محمود',
  },
  {
    id: 5,
    question: 'هل الماء يتجمد عند درجة حرارة 0 مئوية؟',
    type: 'trueFalse',
    category: 'Ministerial',
    correctAnswer: 'True',
    choices: null,
    questionImage: null,
    curriculumId: 2,
    subjectId: 2,
    unitId: 3,
    lessonId: 5,
    year: '2023',
    formNumber: '3',
    curriculum: 'المرحلة المتوسطة',
    subject: 'العلوم',
    unit: 'الوحدة الثالثة',
    lesson: 'الدرس الخامس',
    addedBy: 'محمد حسن',
  },
  {
    id: 6,
    question: 'ما هو العدد الأولي الأصغر؟',
    type: 'multipleChoice',
    category: 'Enrichment',
    correctAnswer: 'choiceA',
    choices: ['2', '1', '3', '5'],
    questionImage: null,
    curriculumId: 1,
    subjectId: 1,
    unitId: 2,
    lessonId: 6,
    year: null,
    formNumber: null,
    curriculum: 'المرحلة الابتدائية',
    subject: 'الرياضيات',
    unit: 'الوحدة الثانية',
    lesson: 'الدرس السادس',
    addedBy: 'نورا إبراهيم',
  },
  {
    id: 7,
    question: 'ما هي لغة البرمجة المستخدمة في تطوير الويب؟',
    type: 'multipleChoice',
    category: 'Enrichment',
    correctAnswer: 'choiceD',
    choices: ['C++', 'Java', 'Python', 'JavaScript'],
    questionImage: null,
    curriculumId: 3,
    subjectId: 3,
    unitId: 4,
    lessonId: 7,
    year: null,
    formNumber: null,
    curriculum: 'المرحلة الثانوية',
    subject: 'الحاسوب',
    unit: 'الوحدة الرابعة',
    lesson: 'الدرس السابع',
    addedBy: 'علي يوسف',
  },
  {
    id: 8,
    question: 'هل القارة القطبية الجنوبية مأهولة بالسكان بشكل دائم؟',
    type: 'trueFalse',
    category: 'Ministerial',
    correctAnswer: 'False',
    choices: null,
    questionImage: null,
    curriculumId: 2,
    subjectId: 4,
    unitId: 5,
    lessonId: 8,
    year: '2024',
    formNumber: '1',
    curriculum: 'المرحلة المتوسطة',
    subject: 'الجغرافيا',
    unit: 'الوحدة الخامسة',
    lesson: 'الدرس الثامن',
    addedBy: 'ليلى أحمد',
  },
  {
    id: 9,
    question: 'ما هو ناتج ضرب 7 × 8؟',
    type: 'multipleChoice',
    category: 'Ministerial',
    correctAnswer: 'choiceB',
    choices: ['54', '56', '58', '60'],
    questionImage: null,
    curriculumId: 1,
    subjectId: 1,
    unitId: 3,
    lessonId: 9,
    year: '2024',
    formNumber: '2',
    curriculum: 'المرحلة الابتدائية',
    subject: 'الرياضيات',
    unit: 'الوحدة الثالثة',
    lesson: 'الدرس التاسع',
    addedBy: 'حسام الدين',
  },
  {
    id: 10,
    question: 'هل الكلوروفيل مسؤول عن عملية البناء الضوئي في النباتات؟',
    type: 'trueFalse',
    category: 'Enrichment',
    correctAnswer: 'True',
    choices: null,
    questionImage: null,
    curriculumId: 2,
    subjectId: 2,
    unitId: 6,
    lessonId: 10,
    year: null,
    formNumber: null,
    curriculum: 'المرحلة المتوسطة',
    subject: 'العلوم',
    unit: 'الوحدة السادسة',
    lesson: 'الدرس العاشر',
    addedBy: 'ريم عبدالله',
  },
];

export default dummyQuestions;
