/**
 * Dummy Questions Data
 *
 * Sample question data for development and testing purposes
 * This file contains mock question objects that match the expected question structure
 */

export const dummyQuestions = [
  {
    id: 1,
    Question: 'ما هي عاصمة المملكة العربية السعودية؟',
    Type: 'MultipleChoice',
    Category: 'Ministerial',
    CorrectAnswer: 'ChoiceA',
    Choices: ['الرياض', 'جدة', 'الدمام', 'المدينة المنورة'],
    QuestionImage: null,
    CurriculumId: 1,
    SubjectId: 1,
    UnitId: 1,
    LessonId: 1,
    Year: '2024',
    FormNumber: '1',
    Grade: 'المرحلة الابتدائية',
    Subject: 'الرياضيات',
    Unit: 'الوحدة الأولى',
    Lesson: 'الدرس الأول',
    AddedBy: 'أحمد محمد',
  },
  {
    id: 2,
    Question: 'ما هو ناتج جمع 5 + 3؟',
    Type: 'MultipleChoice',
    Category: 'Enrichment',
    CorrectAnswer: 'ChoiceB',
    Choices: ['6', '8', '7', '9'],
    QuestionImage: null,
    CurriculumId: 1,
    SubjectId: 1,
    UnitId: 1,
    LessonId: 2,
    Year: null,
    FormNumber: null,
    Curriculum: 'المرحلة الابتدائية',
    Subject: 'الرياضيات',
    Unit: 'الوحدة الأولى',
    Lesson: 'الدرس الثاني',
    AddedBy: 'فاطمة علي',
  },
  {
    id: 3,
    Question: 'هل الشمس كوكب؟',
    Type: 'TrueFalse',
    Category: 'Ministerial',
    CorrectAnswer: 'False',
    Choices: null,
    QuestionImage: null,
    CurriculumId: 2,
    SubjectId: 2,
    UnitId: 2,
    LessonId: 3,
    Year: '2024',
    FormNumber: '2',
    Curriculum: 'المرحلة المتوسطة',
    Subject: 'العلوم',
    Unit: 'الوحدة الثانية',
    Lesson: 'الدرس الثالث',
    AddedBy: 'خالد أحمد',
  },
  {
    id: 4,
    Question: 'ما هو أكبر كوكب في المجموعة الشمسية؟',
    Type: 'MultipleChoice',
    Category: 'Enrichment',
    CorrectAnswer: 'ChoiceC',
    Choices: ['الأرض', 'المريخ', 'المشتري', 'زحل'],
    QuestionImage: 'https://example.com/planet-image.jpg',
    CurriculumId: 2,
    SubjectId: 2,
    UnitId: 2,
    LessonId: 4,
    Year: null,
    FormNumber: null,
    Curriculum: 'المرحلة المتوسطة',
    Subject: 'العلوم',
    Unit: 'الوحدة الثانية',
    Lesson: 'الدرس الرابع',
    AddedBy: 'سارة محمود',
  },
  {
    id: 5,
    Question: 'هل الماء يتجمد عند درجة حرارة 0 مئوية؟',
    Type: 'TrueFalse',
    Category: 'Ministerial',
    CorrectAnswer: 'True',
    Choices: null,
    QuestionImage: null,
    CurriculumId: 2,
    SubjectId: 2,
    UnitId: 3,
    LessonId: 5,
    Year: '2023',
    FormNumber: '3',
    Curriculum: 'المرحلة المتوسطة',
    Subject: 'العلوم',
    Unit: 'الوحدة الثالثة',
    Lesson: 'الدرس الخامس',
    AddedBy: 'محمد حسن',
  },
  {
    id: 6,
    Question: 'ما هو العدد الأولي الأصغر؟',
    Type: 'MultipleChoice',
    Category: 'Enrichment',
    CorrectAnswer: 'ChoiceA',
    Choices: ['2', '1', '3', '5'],
    QuestionImage: null,
    CurriculumId: 1,
    SubjectId: 1,
    UnitId: 2,
    LessonId: 6,
    Year: null,
    FormNumber: null,
    Curriculum: 'المرحلة الابتدائية',
    Subject: 'الرياضيات',
    Unit: 'الوحدة الثانية',
    Lesson: 'الدرس السادس',
    AddedBy: 'نورا إبراهيم',
  },
  {
    id: 7,
    Question: 'ما هي لغة البرمجة المستخدمة في تطوير الويب؟',
    Type: 'MultipleChoice',
    Category: 'Enrichment',
    CorrectAnswer: 'ChoiceD',
    Choices: ['C++', 'Java', 'Python', 'JavaScript'],
    QuestionImage: null,
    CurriculumId: 3,
    SubjectId: 3,
    UnitId: 4,
    LessonId: 7,
    Year: null,
    FormNumber: null,
    Curriculum: 'المرحلة الثانوية',
    Subject: 'الحاسوب',
    Unit: 'الوحدة الرابعة',
    Lesson: 'الدرس السابع',
    AddedBy: 'علي يوسف',
  },
  {
    id: 8,
    Question: 'هل القارة القطبية الجنوبية مأهولة بالسكان بشكل دائم؟',
    Type: 'TrueFalse',
    Category: 'Ministerial',
    CorrectAnswer: 'False',
    Choices: null,
    QuestionImage: null,
    CurriculumId: 2,
    SubjectId: 4,
    UnitId: 5,
    LessonId: 8,
    Year: '2024',
    FormNumber: '1',
    Curriculum: 'المرحلة المتوسطة',
    Subject: 'الجغرافيا',
    Unit: 'الوحدة الخامسة',
    Lesson: 'الدرس الثامن',
    AddedBy: 'ليلى أحمد',
  },
  {
    id: 9,
    Question: 'ما هو ناتج ضرب 7 × 8؟',
    Type: 'MultipleChoice',
    Category: 'Ministerial',
    CorrectAnswer: 'ChoiceB',
    Choices: ['54', '56', '58', '60'],
    QuestionImage: null,
    CurriculumId: 1,
    SubjectId: 1,
    UnitId: 3,
    LessonId: 9,
    Year: '2024',
    FormNumber: '2',
    Curriculum: 'المرحلة الابتدائية',
    Subject: 'الرياضيات',
    Unit: 'الوحدة الثالثة',
    Lesson: 'الدرس التاسع',
    AddedBy: 'حسام الدين',
  },
  {
    id: 10,
    Question: 'هل الكلوروفيل مسؤول عن عملية البناء الضوئي في النباتات؟',
    Type: 'TrueFalse',
    Category: 'Enrichment',
    CorrectAnswer: 'True',
    Choices: null,
    QuestionImage: null,
    CurriculumId: 2,
    SubjectId: 2,
    UnitId: 6,
    LessonId: 10,
    Year: null,
    FormNumber: null,
    Curriculum: 'المرحلة المتوسطة',
    Subject: 'العلوم',
    Unit: 'الوحدة السادسة',
    Lesson: 'الدرس العاشر',
    AddedBy: 'ريم عبدالله',
  },
];

export default dummyQuestions;
