/**
 * Math Symbols Constants
 *
 * Contains all mathematical, physics, chemistry, and biology symbols
 * organized by category for easy access in the MathSymbolsPicker
 */

export const MATH_SYMBOL_CATEGORIES = {
  operators: {
    label: 'Operators',
    labelAr: 'العمليات',
    symbols: [
      { value: '+', label: 'Plus', labelAr: 'زائد' },
      { value: '−', label: 'Minus', labelAr: 'ناقص' },
      { value: '×', label: 'Multiply', labelAr: 'ضرب' },
      { value: '·', label: 'Dot', labelAr: 'نقطة' },
      { value: '÷', label: 'Divide', labelAr: 'قسمة' },
      { value: '/', label: 'Slash', labelAr: 'خط مائل' },
      { value: '=', label: 'Equals', labelAr: 'يساوي' },
      { value: '≠', label: 'Not Equal', labelAr: 'لا يساوي' },
      { value: '≈', label: 'Approximately', labelAr: 'تقريباً' },
      { value: '≅', label: 'Congruent', labelAr: 'متطابق' },
      { value: '≃', label: 'Asymptotically Equal', labelAr: 'متساوي تقريباً' },
      { value: '±', label: 'Plus Minus', labelAr: 'زائد ناقص' },
      { value: '∓', label: 'Minus Plus', labelAr: 'ناقص زائد' },
      { value: '∝', label: 'Proportional', labelAr: 'نسبة' },
      { value: '%', label: 'Percent', labelAr: 'نسبة مئوية' },
      { value: '‰', label: 'Per Mille', labelAr: 'لكل ألف' },
      { value: '°', label: 'Degree', labelAr: 'درجة' },
      { value: '′', label: 'Prime', labelAr: 'أول' },
      { value: '″', label: 'Double Prime', labelAr: 'ثاني' },
    ],
  },
  relations: {
    label: 'Relations',
    labelAr: 'العلاقات',
    symbols: [
      { value: '<', label: 'Less Than', labelAr: 'أصغر من' },
      { value: '>', label: 'Greater Than', labelAr: 'أكبر من' },
      { value: '≤', label: 'Less or Equal', labelAr: 'أصغر أو يساوي' },
      { value: '≥', label: 'Greater or Equal', labelAr: 'أكبر أو يساوي' },
      { value: '≪', label: 'Much Less', labelAr: 'أصغر بكثير' },
      { value: '≫', label: 'Much Greater', labelAr: 'أكبر بكثير' },
      { value: '≲', label: 'Less or Equivalent', labelAr: 'أصغر أو مكافئ' },
      { value: '≳', label: 'Greater or Equivalent', labelAr: 'أكبر أو مكافئ' },
      { value: '∈', label: 'Element Of', labelAr: 'عنصر من' },
      { value: '∉', label: 'Not Element Of', labelAr: 'ليس عنصر من' },
      { value: '∋', label: 'Contains', labelAr: 'يحتوي' },
      { value: '⊂', label: 'Subset', labelAr: 'مجموعة فرعية' },
      { value: '⊃', label: 'Superset', labelAr: 'مجموعة شاملة' },
      { value: '⊆', label: 'Subset or Equal', labelAr: 'مجموعة فرعية أو يساوي' },
      { value: '⊇', label: 'Superset or Equal', labelAr: 'مجموعة شاملة أو يساوي' },
      { value: '⊄', label: 'Not Subset', labelAr: 'ليست مجموعة فرعية' },
      { value: '⊅', label: 'Not Superset', labelAr: 'ليست مجموعة شاملة' },
      { value: '∪', label: 'Union', labelAr: 'اتحاد' },
      { value: '∩', label: 'Intersection', labelAr: 'تقاطع' },
      { value: '∖', label: 'Set Difference', labelAr: 'فرق المجموعات' },
      { value: '∅', label: 'Empty Set', labelAr: 'مجموعة فارغة' },
    ],
  },
  greek: {
    label: 'Greek Letters',
    labelAr: 'الحروف اليونانية',
    symbols: [
      { value: 'α', label: 'Alpha', labelAr: 'ألفا' },
      { value: 'β', label: 'Beta', labelAr: 'بيتا' },
      { value: 'γ', label: 'Gamma', labelAr: 'جاما' },
      { value: 'δ', label: 'Delta', labelAr: 'دلتا' },
      { value: 'ε', label: 'Epsilon', labelAr: 'إبسيلون' },
      { value: 'ζ', label: 'Zeta', labelAr: 'زيتا' },
      { value: 'η', label: 'Eta', labelAr: 'إيتا' },
      { value: 'θ', label: 'Theta', labelAr: 'ثيتا' },
      { value: 'ι', label: 'Iota', labelAr: 'أيوتا' },
      { value: 'κ', label: 'Kappa', labelAr: 'كابا' },
      { value: 'λ', label: 'Lambda', labelAr: 'لامدا' },
      { value: 'μ', label: 'Mu', labelAr: 'مو' },
      { value: 'ν', label: 'Nu', labelAr: 'نو' },
      { value: 'ξ', label: 'Xi', labelAr: 'كسي' },
      { value: 'π', label: 'Pi', labelAr: 'باي' },
      { value: 'ρ', label: 'Rho', labelAr: 'رو' },
      { value: 'σ', label: 'Sigma', labelAr: 'سيجما' },
      { value: 'τ', label: 'Tau', labelAr: 'تاو' },
      { value: 'υ', label: 'Upsilon', labelAr: 'أبسيلون' },
      { value: 'φ', label: 'Phi', labelAr: 'فاي' },
      { value: 'χ', label: 'Chi', labelAr: 'خي' },
      { value: 'ψ', label: 'Psi', labelAr: 'بسي' },
      { value: 'ω', label: 'Omega', labelAr: 'أوميغا' },
      { value: 'Α', label: 'Alpha (Capital)', labelAr: 'ألفا (كبير)' },
      { value: 'Β', label: 'Beta (Capital)', labelAr: 'بيتا (كبير)' },
      { value: 'Γ', label: 'Gamma (Capital)', labelAr: 'جاما (كبير)' },
      { value: 'Δ', label: 'Delta (Capital)', labelAr: 'دلتا (كبير)' },
      { value: 'Ε', label: 'Epsilon (Capital)', labelAr: 'إبسيلون (كبير)' },
      { value: 'Θ', label: 'Theta (Capital)', labelAr: 'ثيتا (كبير)' },
      { value: 'Λ', label: 'Lambda (Capital)', labelAr: 'لامدا (كبير)' },
      { value: 'Ξ', label: 'Xi (Capital)', labelAr: 'كسي (كبير)' },
      { value: 'Π', label: 'Pi (Capital)', labelAr: 'باي (كبير)' },
      { value: 'Σ', label: 'Sigma (Capital)', labelAr: 'سيجما (كبير)' },
      { value: 'Φ', label: 'Phi (Capital)', labelAr: 'فاي (كبير)' },
      { value: 'Ψ', label: 'Psi (Capital)', labelAr: 'بسي (كبير)' },
      { value: 'Ω', label: 'Omega (Capital)', labelAr: 'أوميغا (كبير)' },
    ],
  },
  chemistry: {
    label: 'Chemistry',
    labelAr: 'الكيمياء',
    symbols: [
      { value: '→', label: 'Arrow Right', labelAr: 'سهم يمين' },
      { value: '←', label: 'Arrow Left', labelAr: 'سهم يسار' },
      { value: '↔', label: 'Reversible', labelAr: 'قابل للعكس' },
      { value: '⇌', label: 'Equilibrium', labelAr: 'توازن' },
      { value: '⇄', label: 'Reversible Reaction', labelAr: 'تفاعل قابل للعكس' },
      { value: '⇋', label: 'Equilibrium Arrow', labelAr: 'سهم التوازن' },
      { value: '↑', label: 'Up Arrow', labelAr: 'سهم علوي' },
      { value: '↓', label: 'Down Arrow', labelAr: 'سهم سفلي' },
      { value: '⇑', label: 'Double Up Arrow', labelAr: 'سهم علوي مزدوج' },
      { value: '⇓', label: 'Double Down Arrow', labelAr: 'سهم سفلي مزدوج' },
      { value: 'H₂O', label: 'Water', labelAr: 'ماء' },
      { value: 'CO₂', label: 'Carbon Dioxide', labelAr: 'ثاني أكسيد الكربون' },
      { value: 'NaCl', label: 'Sodium Chloride', labelAr: 'كلوريد الصوديوم' },
      { value: 'H₂SO₄', label: 'Sulfuric Acid', labelAr: 'حمض الكبريتيك' },
      { value: 'NH₃', label: 'Ammonia', labelAr: 'الأمونيا' },
      { value: 'O₂', label: 'Oxygen', labelAr: 'الأكسجين' },
      { value: 'H₂', label: 'Hydrogen', labelAr: 'الهيدروجين' },
      { value: 'N₂', label: 'Nitrogen', labelAr: 'النيتروجين' },
      { value: 'Cl₂', label: 'Chlorine', labelAr: 'الكلور' },
      { value: 'Br₂', label: 'Bromine', labelAr: 'البروم' },
      { value: 'I₂', label: 'Iodine', labelAr: 'اليود' },
      { value: 'F₂', label: 'Fluorine', labelAr: 'الفلور' },
      { value: 'HCl', label: 'Hydrochloric Acid', labelAr: 'حمض الهيدروكلوريك' },
      { value: 'HNO₃', label: 'Nitric Acid', labelAr: 'حمض النيتريك' },
      { value: 'NaOH', label: 'Sodium Hydroxide', labelAr: 'هيدروكسيد الصوديوم' },
      { value: 'CaCO₃', label: 'Calcium Carbonate', labelAr: 'كربونات الكالسيوم' },
      { value: 'CH₄', label: 'Methane', labelAr: 'الميثان' },
      { value: 'C₆H₁₂O₆', label: 'Glucose', labelAr: 'الجلوكوز' },
    ],
  },
  fractions: {
    label: 'Fractions',
    labelAr: 'الكسور',
    symbols: [
      { value: '½', label: '1/2', labelAr: 'نصف' },
      { value: '⅓', label: '1/3', labelAr: 'ثلث' },
      { value: '⅔', label: '2/3', labelAr: 'ثلثان' },
      { value: '¼', label: '1/4', labelAr: 'ربع' },
      { value: '¾', label: '3/4', labelAr: 'ثلاثة أرباع' },
      { value: '⅕', label: '1/5', labelAr: 'خمس' },
      { value: '⅖', label: '2/5', labelAr: 'خمسان' },
      { value: '⅗', label: '3/5', labelAr: 'ثلاثة أخماس' },
      { value: '⅘', label: '4/5', labelAr: 'أربعة أخماس' },
      { value: '⅙', label: '1/6', labelAr: 'سدس' },
      { value: '⅚', label: '5/6', labelAr: 'خمسة أسداس' },
      { value: '⅛', label: '1/8', labelAr: 'ثمن' },
      { value: '⅜', label: '3/8', labelAr: 'ثلاثة أثمان' },
      { value: '⅝', label: '5/8', labelAr: 'خمسة أثمان' },
      { value: '⅞', label: '7/8', labelAr: 'سبعة أثمان' },
    ],
  },
  superscript: {
    label: 'Superscript',
    labelAr: 'الأس',
    symbols: [
      { value: '¹', label: 'Power 1', labelAr: 'أس 1' },
      { value: '²', label: 'Squared', labelAr: 'مربع' },
      { value: '³', label: 'Cubed', labelAr: 'مكعب' },
      { value: '⁴', label: 'Power 4', labelAr: 'أس 4' },
      { value: '⁵', label: 'Power 5', labelAr: 'أس 5' },
      { value: '⁶', label: 'Power 6', labelAr: 'أس 6' },
      { value: '⁷', label: 'Power 7', labelAr: 'أس 7' },
      { value: '⁸', label: 'Power 8', labelAr: 'أس 8' },
      { value: '⁹', label: 'Power 9', labelAr: 'أس 9' },
      { value: '⁰', label: 'Power 0', labelAr: 'أس 0' },
    ],
  },
  subscript: {
    label: 'Subscript',
    labelAr: 'الأس السفلي',
    symbols: [
      { value: '₁', label: 'Sub 1', labelAr: 'أس سفلي 1' },
      { value: '₂', label: 'Sub 2', labelAr: 'أس سفلي 2' },
      { value: '₃', label: 'Sub 3', labelAr: 'أس سفلي 3' },
      { value: '₄', label: 'Sub 4', labelAr: 'أس سفلي 4' },
      { value: '₅', label: 'Sub 5', labelAr: 'أس سفلي 5' },
      { value: '₆', label: 'Sub 6', labelAr: 'أس سفلي 6' },
      { value: '₇', label: 'Sub 7', labelAr: 'أس سفلي 7' },
      { value: '₈', label: 'Sub 8', labelAr: 'أس سفلي 8' },
      { value: '₉', label: 'Sub 9', labelAr: 'أس سفلي 9' },
      { value: '₀', label: 'Sub 0', labelAr: 'أس سفلي 0' },
    ],
  },
  geometry: {
    label: 'Geometry',
    labelAr: 'الهندسة',
    symbols: [
      { value: '∠', label: 'Angle', labelAr: 'زاوية' },
      { value: '∡', label: 'Measured Angle', labelAr: 'زاوية مقاسة' },
      { value: '∢', label: 'Spherical Angle', labelAr: 'زاوية كروية' },
      { value: '°', label: 'Degree', labelAr: 'درجة' },
      { value: '′', label: 'Minute', labelAr: 'دقيقة' },
      { value: '″', label: 'Second', labelAr: 'ثانية' },
      { value: '⊥', label: 'Perpendicular', labelAr: 'عمودي' },
      { value: '∥', label: 'Parallel', labelAr: 'متوازي' },
      { value: '∦', label: 'Not Parallel', labelAr: 'غير متوازي' },
      { value: '△', label: 'Triangle', labelAr: 'مثلث' },
      { value: '▽', label: 'Inverted Triangle', labelAr: 'مثلث مقلوب' },
      { value: '□', label: 'Square', labelAr: 'مربع' },
      { value: '◇', label: 'Diamond', labelAr: 'معين' },
      { value: '○', label: 'Circle', labelAr: 'دائرة' },
      { value: '●', label: 'Filled Circle', labelAr: 'دائرة مملوءة' },
      { value: '◯', label: 'Large Circle', labelAr: 'دائرة كبيرة' },
      { value: '◊', label: 'Lozenge', labelAr: 'معين' },
      { value: '◻', label: 'White Square', labelAr: 'مربع أبيض' },
      { value: '◼', label: 'Black Square', labelAr: 'مربع أسود' },
      { value: 'π', label: 'Pi', labelAr: 'باي' },
      { value: '∟', label: 'Right Angle', labelAr: 'زاوية قائمة' },
      { value: '⊿', label: 'Right Triangle', labelAr: 'مثلث قائم' },
    ],
  },
  calculus: {
    label: 'Calculus',
    labelAr: 'التفاضل والتكامل',
    symbols: [
      { value: '∫', label: 'Integral', labelAr: 'تكامل' },
      { value: '∬', label: 'Double Integral', labelAr: 'تكامل مزدوج' },
      { value: '∭', label: 'Triple Integral', labelAr: 'تكامل ثلاثي' },
      { value: '∮', label: 'Contour Integral', labelAr: 'تكامل كفافي' },
      { value: '∯', label: 'Surface Integral', labelAr: 'تكامل سطح' },
      { value: '∰', label: 'Volume Integral', labelAr: 'تكامل حجم' },
      { value: '∂', label: 'Partial Derivative', labelAr: 'مشتق جزئي' },
      { value: '∇', label: 'Nabla', labelAr: 'نابلا' },
      { value: '∆', label: 'Laplacian', labelAr: 'لابلاسي' },
      { value: '∑', label: 'Sum', labelAr: 'مجموع' },
      { value: '∏', label: 'Product', labelAr: 'حاصل ضرب' },
      { value: '∞', label: 'Infinity', labelAr: 'اللانهاية' },
      { value: '√', label: 'Square Root', labelAr: 'جذر تربيعي' },
      { value: '∛', label: 'Cube Root', labelAr: 'جذر تكعيبي' },
      { value: '∜', label: 'Fourth Root', labelAr: 'جذر رابع' },
      { value: 'lim', label: 'Limit', labelAr: 'نهاية' },
      { value: '→', label: 'Tends To', labelAr: 'يميل إلى' },
      { value: 'd', label: 'Differential', labelAr: 'تفاضل' },
    ],
  },
  physics: {
    label: 'Physics',
    labelAr: 'الفيزياء',
    symbols: [
      { value: 'ℏ', label: 'Planck Constant', labelAr: 'ثابت بلانك' },
      { value: 'c', label: 'Speed of Light', labelAr: 'سرعة الضوء' },
      { value: 'G', label: 'Gravitational Constant', labelAr: 'ثابت الجاذبية' },
      { value: 'k', label: 'Boltzmann Constant', labelAr: 'ثابت بولتزمان' },
      { value: 'ε₀', label: 'Vacuum Permittivity', labelAr: 'سماحية الفراغ' },
      { value: 'μ₀', label: 'Vacuum Permeability', labelAr: 'نفاذية الفراغ' },
      { value: 'e', label: 'Elementary Charge', labelAr: 'شحنة أولية' },
      { value: 'mₑ', label: 'Electron Mass', labelAr: 'كتلة الإلكترون' },
      { value: 'mₚ', label: 'Proton Mass', labelAr: 'كتلة البروتون' },
      { value: 'F', label: 'Force', labelAr: 'قوة' },
      { value: 'E', label: 'Energy', labelAr: 'طاقة' },
      { value: 'P', label: 'Power', labelAr: 'قدرة' },
      { value: 'V', label: 'Voltage', labelAr: 'جهد' },
      { value: 'I', label: 'Current', labelAr: 'تيار' },
      { value: 'R', label: 'Resistance', labelAr: 'مقاومة' },
      { value: 'C', label: 'Capacitance', labelAr: 'سعة' },
      { value: 'L', label: 'Inductance', labelAr: 'حث' },
      { value: 'ρ', label: 'Density', labelAr: 'كثافة' },
      { value: 'λ', label: 'Wavelength', labelAr: 'طول الموجة' },
      { value: 'ν', label: 'Frequency', labelAr: 'تردد' },
      { value: 'f', label: 'Frequency', labelAr: 'تردد' },
      { value: 'T', label: 'Temperature', labelAr: 'درجة الحرارة' },
      { value: 'θ', label: 'Angle', labelAr: 'زاوية' },
      { value: 'ω', label: 'Angular Frequency', labelAr: 'التردد الزاوي' },
      { value: 'τ', label: 'Torque', labelAr: 'عزم الدوران' },
      { value: 'J', label: 'Moment of Inertia', labelAr: 'عزم القصور الذاتي' },
    ],
  },
  logic: {
    label: 'Logic',
    labelAr: 'المنطق',
    symbols: [
      { value: '∧', label: 'And', labelAr: 'و' },
      { value: '∨', label: 'Or', labelAr: 'أو' },
      { value: '¬', label: 'Not', labelAr: 'ليس' },
      { value: '⊕', label: 'XOR', labelAr: 'أو الحصري' },
      { value: '⊻', label: 'XOR', labelAr: 'أو الحصري' },
      { value: '⊼', label: 'NAND', labelAr: 'ليس و' },
      { value: '⊽', label: 'NOR', labelAr: 'ليس أو' },
      { value: '⇒', label: 'Implies', labelAr: 'يستلزم' },
      { value: '⇐', label: 'Implied By', labelAr: 'مستلزم من' },
      { value: '⇔', label: 'If and Only If', labelAr: 'إذا وفقط إذا' },
      { value: '∀', label: 'For All', labelAr: 'لكل' },
      { value: '∃', label: 'There Exists', labelAr: 'يوجد' },
      { value: '∄', label: 'There Does Not Exist', labelAr: 'لا يوجد' },
      { value: '∴', label: 'Therefore', labelAr: 'لذلك' },
      { value: '∵', label: 'Because', labelAr: 'لأن' },
      { value: '⊤', label: 'True', labelAr: 'صحيح' },
      { value: '⊥', label: 'False', labelAr: 'خطأ' },
    ],
  },
  statistics: {
    label: 'Statistics',
    labelAr: 'الإحصاء',
    symbols: [
      { value: 'μ', label: 'Mean', labelAr: 'المتوسط' },
      { value: 'σ', label: 'Standard Deviation', labelAr: 'الانحراف المعياري' },
      { value: 'σ²', label: 'Variance', labelAr: 'التباين' },
      { value: 'x̄', label: 'Sample Mean', labelAr: 'متوسط العينة' },
      { value: 'ȳ', label: 'Sample Mean Y', labelAr: 'متوسط العينة Y' },
      { value: 's', label: 'Sample Standard Deviation', labelAr: 'انحراف العينة المعياري' },
      { value: 's²', label: 'Sample Variance', labelAr: 'تباين العينة' },
      { value: 'n', label: 'Sample Size', labelAr: 'حجم العينة' },
      { value: 'N', label: 'Population Size', labelAr: 'حجم المجتمع' },
      { value: 'p', label: 'Probability', labelAr: 'الاحتمال' },
      { value: 'P', label: 'Probability', labelAr: 'الاحتمال' },
      { value: 'E', label: 'Expected Value', labelAr: 'القيمة المتوقعة' },
      { value: 'Var', label: 'Variance', labelAr: 'التباين' },
      { value: 'Cov', label: 'Covariance', labelAr: 'التغاير' },
      { value: 'Corr', label: 'Correlation', labelAr: 'الارتباط' },
      { value: 'ρ', label: 'Correlation Coefficient', labelAr: 'معامل الارتباط' },
      { value: 'r', label: 'Sample Correlation', labelAr: 'ارتباط العينة' },
      { value: 'χ²', label: 'Chi-Squared', labelAr: 'كاي مربع' },
      { value: 't', label: 't-Statistic', labelAr: 'إحصائية t' },
      { value: 'z', label: 'z-Score', labelAr: 'قيمة z' },
      { value: 'α', label: 'Significance Level', labelAr: 'مستوى الدلالة' },
      { value: 'β', label: 'Type II Error', labelAr: 'خطأ النوع الثاني' },
      { value: 'H₀', label: 'Null Hypothesis', labelAr: 'الفرضية الصفرية' },
      { value: 'H₁', label: 'Alternative Hypothesis', labelAr: 'الفرضية البديلة' },
    ],
  },
  arrows: {
    label: 'Arrows',
    labelAr: 'الأسهم',
    symbols: [
      { value: '→', label: 'Right Arrow', labelAr: 'سهم يمين' },
      { value: '←', label: 'Left Arrow', labelAr: 'سهم يسار' },
      { value: '↑', label: 'Up Arrow', labelAr: 'سهم علوي' },
      { value: '↓', label: 'Down Arrow', labelAr: 'سهم سفلي' },
      { value: '↔', label: 'Left-Right Arrow', labelAr: 'سهم يسار-يمين' },
      { value: '↕', label: 'Up-Down Arrow', labelAr: 'سهم علوي-سفلي' },
      { value: '⇒', label: 'Double Right Arrow', labelAr: 'سهم مزدوج يمين' },
      { value: '⇐', label: 'Double Left Arrow', labelAr: 'سهم مزدوج يسار' },
      { value: '⇑', label: 'Double Up Arrow', labelAr: 'سهم مزدوج علوي' },
      { value: '⇓', label: 'Double Down Arrow', labelAr: 'سهم مزدوج سفلي' },
      { value: '⇔', label: 'Double Left-Right Arrow', labelAr: 'سهم مزدوج يسار-يمين' },
      { value: '⇕', label: 'Double Up-Down Arrow', labelAr: 'سهم مزدوج علوي-سفلي' },
      { value: '↗', label: 'North-East Arrow', labelAr: 'سهم شمال شرق' },
      { value: '↘', label: 'South-East Arrow', labelAr: 'سهم جنوب شرق' },
      { value: '↙', label: 'South-West Arrow', labelAr: 'سهم جنوب غرب' },
      { value: '↖', label: 'North-West Arrow', labelAr: 'سهم شمال غرب' },
      { value: '⟶', label: 'Long Right Arrow', labelAr: 'سهم طويل يمين' },
      { value: '⟵', label: 'Long Left Arrow', labelAr: 'سهم طويل يسار' },
      { value: '⟷', label: 'Long Left-Right Arrow', labelAr: 'سهم طويل يسار-يمين' },
      { value: '↦', label: 'Maps To', labelAr: 'يرسم إلى' },
      { value: '↪', label: 'Right Arrow with Hook', labelAr: 'سهم يمين مع خطاف' },
      { value: '↩', label: 'Left Arrow with Hook', labelAr: 'سهم يسار مع خطاف' },
    ],
  },
  units: {
    label: 'Units',
    labelAr: 'الوحدات',
    symbols: [
      { value: 'm', label: 'Meter', labelAr: 'متر' },
      { value: 'kg', label: 'Kilogram', labelAr: 'كيلوجرام' },
      { value: 's', label: 'Second', labelAr: 'ثانية' },
      { value: 'A', label: 'Ampere', labelAr: 'أمبير' },
      { value: 'K', label: 'Kelvin', labelAr: 'كلفن' },
      { value: 'mol', label: 'Mole', labelAr: 'مول' },
      { value: 'cd', label: 'Candela', labelAr: 'كانديلا' },
      { value: 'Hz', label: 'Hertz', labelAr: 'هيرتز' },
      { value: 'N', label: 'Newton', labelAr: 'نيوتن' },
      { value: 'J', label: 'Joule', labelAr: 'جول' },
      { value: 'W', label: 'Watt', labelAr: 'واط' },
      { value: 'Pa', label: 'Pascal', labelAr: 'باسكال' },
      { value: 'V', label: 'Volt', labelAr: 'فولت' },
      { value: 'Ω', label: 'Ohm', labelAr: 'أوم' },
      { value: 'C', label: 'Coulomb', labelAr: 'كولوم' },
      { value: 'F', label: 'Farad', labelAr: 'فاراد' },
      { value: 'H', label: 'Henry', labelAr: 'هنري' },
      { value: 'T', label: 'Tesla', labelAr: 'تسلا' },
      { value: 'Wb', label: 'Weber', labelAr: 'ويبر' },
      { value: 'lm', label: 'Lumen', labelAr: 'لومن' },
      { value: 'lx', label: 'Lux', labelAr: 'لوكس' },
      { value: 'Bq', label: 'Becquerel', labelAr: 'بيكريل' },
      { value: 'Gy', label: 'Gray', labelAr: 'جراي' },
      { value: 'Sv', label: 'Sievert', labelAr: 'سيفرت' },
      { value: 'kat', label: 'Katal', labelAr: 'كاتال' },
    ],
  },
  special: {
    label: 'Special',
    labelAr: 'خاص',
    symbols: [
      { value: 'ℕ', label: 'Natural Numbers', labelAr: 'الأعداد الطبيعية' },
      { value: 'ℤ', label: 'Integers', labelAr: 'الأعداد الصحيحة' },
      { value: 'ℚ', label: 'Rational Numbers', labelAr: 'الأعداد النسبية' },
      { value: 'ℝ', label: 'Real Numbers', labelAr: 'الأعداد الحقيقية' },
      { value: 'ℂ', label: 'Complex Numbers', labelAr: 'الأعداد المركبة' },
      { value: 'ℙ', label: 'Prime Numbers', labelAr: 'الأعداد الأولية' },
      { value: '∅', label: 'Empty Set', labelAr: 'مجموعة فارغة' },
      { value: '∅', label: 'Null Set', labelAr: 'مجموعة صفرية' },
      { value: '∞', label: 'Infinity', labelAr: 'اللانهاية' },
      { value: '∝', label: 'Proportional', labelAr: 'نسبة' },
      { value: '~', label: 'Similar', labelAr: 'مشابه' },
      { value: '≈', label: 'Approximately', labelAr: 'تقريباً' },
      { value: '≅', label: 'Congruent', labelAr: 'متطابق' },
      { value: '≡', label: 'Identical', labelAr: 'مطابق' },
      { value: '≢', label: 'Not Identical', labelAr: 'غير مطابق' },
      { value: '≝', label: 'Defined As', labelAr: 'معرّف كـ' },
      { value: '≜', label: 'Equal By Definition', labelAr: 'يساوي بالتعريف' },
      { value: '≐', label: 'Approaches', labelAr: 'يقترب من' },
      { value: '≓', label: 'Image Of', labelAr: 'صورة من' },
      { value: '≔', label: 'Colon Equals', labelAr: 'نقطتان يساوي' },
      { value: '≕', label: 'Equals Colon', labelAr: 'يساوي نقطتان' },
    ],
  },
  algebra: {
    label: 'Algebra',
    labelAr: 'الجبر',
    symbols: [
      { value: 'x', label: 'Variable x', labelAr: 'متغير x' },
      { value: 'y', label: 'Variable y', labelAr: 'متغير y' },
      { value: 'z', label: 'Variable z', labelAr: 'متغير z' },
      { value: 'a', label: 'Coefficient a', labelAr: 'معامل a' },
      { value: 'b', label: 'Coefficient b', labelAr: 'معامل b' },
      { value: 'c', label: 'Coefficient c', labelAr: 'معامل c' },
      { value: 'n', label: 'Natural Number', labelAr: 'عدد طبيعي' },
      { value: 'm', label: 'Natural Number', labelAr: 'عدد طبيعي' },
      { value: 'k', label: 'Constant', labelAr: 'ثابت' },
      { value: 'i', label: 'Imaginary Unit', labelAr: 'الوحدة التخيلية' },
      { value: 'j', label: 'Imaginary Unit', labelAr: 'الوحدة التخيلية' },
      { value: 'e', label: "Euler's Number", labelAr: 'عدد أويلر' },
      { value: 'ln', label: 'Natural Logarithm', labelAr: 'اللوغاريتم الطبيعي' },
      { value: 'log', label: 'Logarithm', labelAr: 'اللوغاريتم' },
      { value: 'lg', label: 'Base 10 Logarithm', labelAr: 'لوغاريتم الأساس 10' },
      { value: 'exp', label: 'Exponential', labelAr: 'الأسي' },
      { value: 'mod', label: 'Modulo', labelAr: 'باقي القسمة' },
      { value: 'gcd', label: 'Greatest Common Divisor', labelAr: 'القاسم المشترك الأكبر' },
      { value: 'lcm', label: 'Least Common Multiple', labelAr: 'المضاعف المشترك الأصغر' },
      { value: '!', label: 'Factorial', labelAr: 'عاملي' },
      { value: 'P', label: 'Permutation', labelAr: 'ترتيب' },
      { value: 'C', label: 'Combination', labelAr: 'توافق' },
      { value: 'bin', label: 'Binomial', labelAr: 'ثنائي الحد' },
    ],
  },
  trigonometry: {
    label: 'Trigonometry',
    labelAr: 'المثلثات',
    symbols: [
      { value: 'sin', label: 'Sine', labelAr: 'جيب' },
      { value: 'cos', label: 'Cosine', labelAr: 'جيب التمام' },
      { value: 'tan', label: 'Tangent', labelAr: 'ظل' },
      { value: 'cot', label: 'Cotangent', labelAr: 'ظل التمام' },
      { value: 'sec', label: 'Secant', labelAr: 'قاطع' },
      { value: 'csc', label: 'Cosecant', labelAr: 'قاطع التمام' },
      { value: 'arcsin', label: 'Arcsine', labelAr: 'الجيب العكسي' },
      { value: 'arccos', label: 'Arccosine', labelAr: 'جيب التمام العكسي' },
      { value: 'arctan', label: 'Arctangent', labelAr: 'الظل العكسي' },
      { value: 'sinh', label: 'Hyperbolic Sine', labelAr: 'الجيب الزائدي' },
      { value: 'cosh', label: 'Hyperbolic Cosine', labelAr: 'جيب التمام الزائدي' },
      { value: 'tanh', label: 'Hyperbolic Tangent', labelAr: 'الظل الزائدي' },
      { value: 'θ', label: 'Angle Theta', labelAr: 'زاوية ثيتا' },
      { value: 'φ', label: 'Angle Phi', labelAr: 'زاوية فاي' },
      { value: 'α', label: 'Angle Alpha', labelAr: 'زاوية ألفا' },
      { value: 'β', label: 'Angle Beta', labelAr: 'زاوية بيتا' },
      { value: 'γ', label: 'Angle Gamma', labelAr: 'زاوية جاما' },
      { value: '°', label: 'Degree', labelAr: 'درجة' },
      { value: 'rad', label: 'Radian', labelAr: 'راديان' },
      { value: 'π', label: 'Pi', labelAr: 'باي' },
      { value: '2π', label: 'Two Pi', labelAr: 'باي مضروب في اثنين' },
    ],
  },
  vectors: {
    label: 'Vectors',
    labelAr: 'المتجهات',
    symbols: [
      { value: '→', label: 'Vector Arrow', labelAr: 'سهم المتجه' },
      { value: '⇀', label: 'Right Arrow Above', labelAr: 'سهم فوق' },
      { value: '⇁', label: 'Right Arrow Above Hook', labelAr: 'سهم فوق مع خطاف' },
      { value: '⇂', label: 'Right Arrow Below', labelAr: 'سهم تحت' },
      { value: 'a⃗', label: 'Vector a', labelAr: 'متجه a' },
      { value: 'b⃗', label: 'Vector b', labelAr: 'متجه b' },
      { value: 'v⃗', label: 'Vector v', labelAr: 'متجه v' },
      { value: 'u⃗', label: 'Vector u', labelAr: 'متجه u' },
      { value: '×', label: 'Cross Product', labelAr: 'الضرب الاتجاهي' },
      { value: '·', label: 'Dot Product', labelAr: 'الضرب النقطي' },
      { value: '||', label: 'Magnitude', labelAr: 'المقدار' },
      { value: '|', label: 'Absolute Value', labelAr: 'القيمة المطلقة' },
      { value: '⊥', label: 'Perpendicular', labelAr: 'عمودي' },
      { value: '∥', label: 'Parallel', labelAr: 'متوازي' },
      { value: '∠', label: 'Angle', labelAr: 'زاوية' },
      { value: 'î', label: 'Unit Vector i', labelAr: 'متجه الوحدة i' },
      { value: 'ĵ', label: 'Unit Vector j', labelAr: 'متجه الوحدة j' },
      { value: 'k̂', label: 'Unit Vector k', labelAr: 'متجه الوحدة k' },
      { value: '∇', label: 'Nabla', labelAr: 'نابلا' },
      { value: '∇·', label: 'Divergence', labelAr: 'التباعد' },
      { value: '∇×', label: 'Curl', labelAr: 'الدوران' },
      { value: '∇²', label: 'Laplacian', labelAr: 'لابلاسي' },
    ],
  },
  matrices: {
    label: 'Matrices',
    labelAr: 'المصفوفات',
    symbols: [
      { value: 'A', label: 'Matrix A', labelAr: 'مصفوفة A' },
      { value: 'B', label: 'Matrix B', labelAr: 'مصفوفة B' },
      { value: 'C', label: 'Matrix C', labelAr: 'مصفوفة C' },
      { value: 'I', label: 'Identity Matrix', labelAr: 'مصفوفة الوحدة' },
      { value: 'O', label: 'Zero Matrix', labelAr: 'مصفوفة الصفر' },
      { value: 'Aᵀ', label: 'Transpose', labelAr: 'منقول' },
      { value: 'A⁻¹', label: 'Inverse', labelAr: 'معكوس' },
      { value: 'A*', label: 'Conjugate Transpose', labelAr: 'منقول مرافق' },
      { value: 'det', label: 'Determinant', labelAr: 'المحدد' },
      { value: '|A|', label: 'Determinant of A', labelAr: 'محدد A' },
      { value: 'tr', label: 'Trace', labelAr: 'الأثر' },
      { value: 'rank', label: 'Rank', labelAr: 'الرتبة' },
      { value: 'dim', label: 'Dimension', labelAr: 'البعد' },
      { value: 'span', label: 'Span', labelAr: 'المدى' },
      { value: 'ker', label: 'Kernel', labelAr: 'النواة' },
      { value: 'im', label: 'Image', labelAr: 'الصورة' },
      { value: 'null', label: 'Null Space', labelAr: 'الفضاء الصفري' },
      { value: 'col', label: 'Column Space', labelAr: 'فضاء الأعمدة' },
      { value: 'row', label: 'Row Space', labelAr: 'فضاء الصفوف' },
      { value: 'eig', label: 'Eigenvalue', labelAr: 'القيمة الذاتية' },
      { value: 'eigen', label: 'Eigenvector', labelAr: 'المتجه الذاتي' },
      { value: '⊗', label: 'Tensor Product', labelAr: 'الضرب التنسوري' },
      { value: '⊕', label: 'Direct Sum', labelAr: 'المجموع المباشر' },
    ],
  },
  biology: {
    label: 'Biology',
    labelAr: 'الأحياء',
    symbols: [
      { value: 'DNA', label: 'DNA', labelAr: 'الحمض النووي الريبوزي منقوص الأكسجين' },
      { value: 'RNA', label: 'RNA', labelAr: 'الحمض النووي الريبوزي' },
      { value: 'ATP', label: 'ATP', labelAr: 'أدينوسين ثلاثي الفوسفات' },
      { value: 'ADP', label: 'ADP', labelAr: 'أدينوسين ثنائي الفوسفات' },
      { value: 'NAD+', label: 'NAD+', labelAr: 'نيكوتيناميد الأدينين ثنائي النوكليوتيد' },
      { value: 'NADH', label: 'NADH', labelAr: 'NADH' },
      { value: 'FAD', label: 'FAD', labelAr: 'فلافين الأدينين ثنائي النوكليوتيد' },
      { value: 'FADH₂', label: 'FADH₂', labelAr: 'FADH₂' },
      { value: 'CO₂', label: 'Carbon Dioxide', labelAr: 'ثاني أكسيد الكربون' },
      { value: 'O₂', label: 'Oxygen', labelAr: 'الأكسجين' },
      { value: 'H₂O', label: 'Water', labelAr: 'الماء' },
      { value: 'NH₃', label: 'Ammonia', labelAr: 'الأمونيا' },
      { value: 'CH₄', label: 'Methane', labelAr: 'الميثان' },
      { value: 'C₆H₁₂O₆', label: 'Glucose', labelAr: 'الجلوكوز' },
      { value: 'C₆H₁₂O₆', label: 'Fructose', labelAr: 'الفركتوز' },
      { value: 'C₁₂H₂₂O₁₁', label: 'Sucrose', labelAr: 'السكروز' },
      { value: 'pH', label: 'pH', labelAr: 'الأس الهيدروجيني' },
      { value: 'pOH', label: 'pOH', labelAr: 'pOH' },
      { value: 'Kₐ', label: 'Acid Dissociation Constant', labelAr: 'ثابت تفكك الحمض' },
      { value: 'Kᵦ', label: 'Base Dissociation Constant', labelAr: 'ثابت تفكك القاعدة' },
      { value: 'Kᵧ', label: 'Equilibrium Constant', labelAr: 'ثابت الاتزان' },
      { value: 'ΔG', label: 'Gibbs Free Energy', labelAr: 'طاقة جيبس الحرة' },
      { value: 'ΔH', label: 'Enthalpy Change', labelAr: 'التغير في المحتوى الحراري' },
      { value: 'ΔS', label: 'Entropy Change', labelAr: 'التغير في الإنتروبيا' },
      { value: 'μ', label: 'Growth Rate', labelAr: 'معدل النمو' },
      { value: 'λ', label: 'Wavelength', labelAr: 'طول الموجة' },
      { value: 'ν', label: 'Frequency', labelAr: 'التردد' },
    ],
  },
};

// جميع الرموز في مصفوفة واحدة للبحث
export const ALL_SYMBOLS = Object.values(MATH_SYMBOL_CATEGORIES).flatMap((category) =>
  category.symbols.map((symbol) => ({ ...symbol, category: category.label }))
);

/**
 * Check if a subject name matches math/science subjects
 * @param {string} subjectName - Subject name (Arabic or English)
 * @returns {boolean} True if subject is math, physics, chemistry, or biology
 */
export const isMathScienceSubject = (subjectName) => {
  if (!subjectName) return false;

  const normalizedName = subjectName.toLowerCase().trim();

  // Arabic subject names
  const arabicSubjects = [
    'رياضيات',
    'الرياضيات',
    'فيزياء',
    'الفيزياء',
    'كيمياء',
    'الكيمياء',
    'أحياء',
    'الأحياء',
    'علوم',
    'العلوم',
  ];

  // English subject names
  const englishSubjects = ['mathematics', 'math', 'physics', 'chemistry', 'biology', 'science'];

  // Check if subject name matches any math/science subject
  // Use exact match or contains (for compound names like "الرياضيات التطبيقية")
  const matchesArabic = arabicSubjects.some(
    (subject) => normalizedName === subject || normalizedName.includes(subject)
  );
  const matchesEnglish = englishSubjects.some(
    (subject) => normalizedName === subject || normalizedName.includes(subject)
  );

  return matchesArabic || matchesEnglish;
};
